project:
  type: book
  output-dir: docs

book:
  title: Summary of U.S. Stock Assessment Workflows
  subtitle: Tools, Templates, and other Resources
  date: April 2024
  downloads: [pdf, docx]
  author:
  - name: Samantha Schiano
    affiliations:
      - id: ecs
        name: ECS Federal in Support of 
        department: NOAA Fisheries Office of Science and Technology
        address: 
          - 1315 East West Highway
          - Silver Spring, MD 20910
  chapters:
    - index.qmd
    - text/summary.qmd
    - text/general-workflow.qmd
    - text/stock-assessment-models.qmd
    - text/tool-and-resources.qmd
    - text/fishery-science-centers.qmd
    - text/conclusions.qmd
    - text/references.qmd

  site-url: https://schiano-noaa.github.io/regional-sa-workflows/
  repo-url: https://github.com/Schiano-NOAA/regional-sa-workflows
  repo-actions: [edit, source, issue]
  search: true

bibliography: 
  - text/references.bib

execute:
  echo: false
  code-overflow: wrap
  freeze: auto

format:
  docx:
    toc: true
    toc-depth: 2
    reference-doc: template.docx
    always_allow_html: true
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
  titlepage-pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    # titlepage: "plain"
    keep-tex: true

filters: 
  - name_crossref.lua
  - titlepage-theme.lua
  - coverpage-theme.lua
    
metadata-files:
  - _frontmatter.yml
  
