# Alaska Fisheries Science Center (AFSC)

## Resources

AFSC takes advantage of multiple packages and templates built to help produce stock assessment reports. They have also built their own tools to improve and streamline their workflows. These tools include:

  -   afscdata
  -   afscassess
  -   safe
  -   r4ss

### afscdata

[Github Repository](https://github.com/afsc-assessments/afscdata/)

This R package was developed in order to extract fishery data for use in analyses and stock assessment models. Various functions query data from a connected database. There are various functions dependent on the target species which extract .csv files with a time stamp of the query.

**Other tools to describe:**

  -   afscassess
  
  -   safe reporting

## Workflow

  -   Full assessments vs. partial assessments vs. model review
  
    -   Add'l harvest projections
    
  -   Operational & stock monitoring update
  
  -   Annual and bi-annual assessments (+ some every 4 yrs)
  
  -   bespoke and SS models
  
#### Assessment Outlines

  -   Outlines as agreed upon in the TOR from council
