# Region Specific Workflow {#sec-regionworkflows}

  - Descriptions of the workflows by region and what separates them from other regions
  
    - Incorporate regional specific TORs or how TORs are developed if species specific and how they guide region workflows
  
  - Advances made by this region and the tools they use
  
  - Particular struggles or unique operations incorporated into their workflow
  
  - Table of resources used for their workflows
  

Note: assessment reports and incorporated materials are all assessment author based outside of their regional requirements

Alternative way to reference section \nameref{sec-safe} rather than @sec-safe
*Note doesn't work with html render.

## AFSC {#sec-afsc}

Process variations:

  - Uses afscData (@sec-afscdata) for data extractions for model inputs
  
    - SQL for data query
  
  - AFSCassess (@sec-afscassess) for cleaning up data, generating figures, and other associated processes with generating a stock assessment report
  
  - Functions tailored to pull data/perform function for each species
  
  - ADMB model outputs
  
  - Utilizes 'safe' (@sec-safe) reporting template
  
    - Automated and reproducible, large effort put into making and maintaining
    
  - Formalized guidelines for reports
    
  
Largest problems:

  - Inheriting an assessment can be a challenge
  
  - Data structures very different in GOA v. BSAI
  
  - Input and output framework needs work
  
  - Large amount of tables and figures (potential to clog the process; is this too many?)

## NEFSC {#sec-nefsc}

Process variations:

  - Informal/verbal agreement for TOR guidelines for each stock
  
  - Standardized report template agreed upon by NOAA and the MAFMC AND NEFMC (agreed on in 2017)
  
    - Short and concise to make policy decisions (mgmt track specifically)
  
  - Report template is not publicly available but all done in latex (modular workflow)
  
    - Figures rendered outside (saved as png) then reference in doc
    
    - Tables created into tex files and referenced as component in template
    
  - Extensive work with 508 compliance
  
    - Contractors developing package for compliance to apply to template
    
Largest problems:

  - Lots of processing variables for 508 compliance
  
  - Even with all the work in the compliance, there is still a large effort into making it accessible (~2 week conversion for single analyst at the center)
  
  - Workflow still labor intensive
  
  - Large barrier to use template for new users
  
  - Only automated for management track reports
  
## NWFSC {#sec-nwfsc}

Process Variations:

  - Input data extractions are from an online database and state agencies
    
    - nwfscSurvey repo for west coast groundfish survey data
  
  - Use of sa4ss (maintained by scientist at NWFSC), package to make a template in github
  
  - All figures generated using r4ss functions
  
  - Standardized tables
  
  - Scripts are specific to species
  
  - Use of SS3 in the NW led to huge developments for packages that are tuned to its output such as r4ss and sa4ss
  
  - Process is not standardized for entire center (common among a lot of centers)
  
    - Some assessment scientists create a new repo for each assessment

Largest Issues:

  - Reproducibility
  
  - Iterative process of incorporating changes to models for report generation: not optomized for this part of the workflow

## PIFSC {#sec-pifsc}

Process variations:

  - "Template" report in github (private and not modular; international)
  
  - No generalized workflow/process (aka each species is a little different)
  
  - Workflow isn't specifically defined
  
  - Process tables and figures in R then incorporate into a word document (domestic)
  
    - Reported out as a tech memo
  
Largest Issues:

  - Work with international and species complexes that make it difficult to have a general reporting structure
  
  - Barrier to entry with quarto
  
  - Can't update .qmd file after changes made to word doc after render
  
  - Parallelization of workflows

## SEFSC {#sec-sefsc}

Process Variations:

  - Follows requirements for SEDAR

  - Figures and tables at the end of the report (SEDAR requirement)
  
  - File system on server where data is stored
  

Caribbean:

  - A lot of intermediaries in the process (aka figures and tables generated outside of the report)
  
  - Incorporated some use of Rmarkdown with a modularized template system
  
  - Prototype template using quarto books for SEDAR 57
  
Gulf of Mexico:

  - Rmarkdown template used in process (private repository on GitHub)
  
  - Work with SS3 report file and automate from there
  
  - Some parameters are hard coded and changed per species
  
  - New forked repo. for each stock assessment
  

South Atlantic:

  - Data is gathered as an excel file - manually converted as inputs for the assessment model (potential for automation but analysts lack time)
  
  - Model process includes: fine tuning, diagnostics, ADMB2R (@sec-admb2r), FishGraph (@sec-fishgraph)
  
  - Uses latex template with tables as outside tex doc (incorporated into the template) and figures produced outside of template into a folder then referenced into template
  
  - Report not completely automated
  
  - Organized on a species by species case
  
  - Template not on github
  
  - Previous reports are shared with analyst who next inherits it through backup drive
  
  
Largest Issues:

  - Variable answer based on region (South Atlantic v. Gulf of Mexico v. Caribbean)
  
  - Confidentiality (large recreational base)
  
  - Data providers don't provide data in the same format
  
  - Limited to no 508 compliance (other than minimum requirements)
  
    - Highly time intensive

Caribbean:
  
  - Difficulty referencing tables and figures in Rmarkdown
  
  - Limited abilities and knowledge with R/quarto
  
  - Oftentimes updates seem to feel like benchmark assessments due to requests
  
Gulf of Mexico:

  - Figures in regards to inputs cause most issues
  
  - Long, large reports
  
  - Steep learning curve for those not yet using markdown (all in the branch have at least used the Rmarkdown template once for an assessment)
  
  - Large data sets/data takes a while to read in
  
  - Cannot access others' SS3 output files dues to confidentiality (those outside of NOAA org)
  
  - Projections aren't standardized
  
South Atlantic:

  - Process is not automated
  
  - Localized reporting template

## SWFSC {#sec-swfsc}

Process Variations:

  - Inherited workflow from analysts 
  
  - Use of 'sa4ss' (@sec-sa4ss) for workflow with some modifications
  
  - Centralized Rmarkdown for process
  
  - Access to past assessments on PFMC GitHub
  
Largest Issues:

  - Data acquisition and handling (also troubles associated with data confidentiality)
  
  - Tough transition for new employees due GitHub used on an analyst-to-analyst bases and unclear workflow structure
  
  - Model versioning and changes to the report through a non-linear process (common among other regions too)
  
  - 508 compliance efforts sometimes break

Example in text reference [@clark1993].
