# Summary

Developing and producing a stock assessment report requires a considerable amount of data consolidation, analysis, and research. Reports can range from 10 pages to well over 300, but the goal of the process remains to provide management advice with the current and projected status of the stock, catches, and other important parameters to ensure its sustainability. There have been many efforts done to improve the reproducibility of workflows and reduce time it takes to produce these reports. So far, improvements and efforts have ranged considerably by region of the U.S. Specifically, each of the seven regional fishery science centers across the U.S. have their own workflows to assess a stock and produce its report. Many of these workflows are guided by requirements from fishery management councils and other involved managing bodies that utilize these reports to delegate fishery regulations. 

Workflows across the country not only range from region to region, but from scientist to scientist. There is no current standardized or accepted best practice for producing a stock assessment report. Some centers rely on the use of latex, a common software to produce documents with in-text calculations, while others utilize more recently developed programs like Rmarkdown and quarto, which both use latex as a basis for their production. Others utilize the capacity of Microsoft word which restricts the reproducibility of a report as well as increases work time since figures, tables, and other associated resources must be compiled outside of the word document.

**Description of interaction and list of fishery management councils across the US**

